# Generated by Django 5.2.4 on 2025-07-25 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
