# Generated by Django 5.2.4 on 2025-07-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0002_content_file_name_problem_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontentprogress',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
