# Generated by Django 5.2.4 on 2025-08-13 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0003_usercontentprogress_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_data', models.JSONField(help_text='Original quiz questions and structure')),
                ('user_answers', models.JSONField(help_text="User's submitted answers")),
                ('score', models.FloatField(help_text='Percentage score achieved')),
                ('passed', models.BooleanField(help_text='Whether the user passed the quiz')),
                ('correct_answers', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('time_taken', models.PositiveIntegerField(help_text='Time taken in seconds')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('content', models.ForeignKey(limit_choices_to={'type': 'QUIZ'}, on_delete=django.db.models.deletion.CASCADE, to='namma_coding_shaale_app.content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namma_coding_shaale_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'content', 'attempt_number')},
            },
        ),
    ]
