# Generated by Django 5.2.4 on 2025-08-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0004_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='correct_answers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='passed',
            field=models.BooleanField(default=False, help_text='Whether the user passed the quiz'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='quiz_data',
            field=models.JSONField(default='{}', help_text='Original quiz questions and structure'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.FloatField(default=0, help_text='Percentage score achieved'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='time_taken',
            field=models.PositiveIntegerField(blank=True, help_text='Time taken in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='total_questions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='user_answers',
            field=models.JSONField(default='{}', help_text="User's submitted answers"),
        ),
    ]
