# Generated by Django 5.2.4 on 2025-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0005_alter_quizsubmission_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='quiz_data',
            field=models.JSONField(default='dict', help_text='Original quiz questions and structure'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='user_answers',
            field=models.JSONField(default='dict', help_text="User's submitted answers"),
        ),
    ]
