# Generated by Django 5.2.4 on 2025-08-14 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0007_alter_quizsubmission_quiz_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('user', 'course', 'content')},
        ),
    ]
