# Generated by Django 5.2.4 on 2025-10-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0008_alter_quizsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20),
        ),
    ]
