# Generated by Django 5.2.4 on 2025-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0009_usercourse_certificate_id_usercourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
