# Generated by Django 5.2.4 on 2025-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0010_alter_usercourse_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('PROBLEM', 'Problem'), ('VIDEO', 'Video'), ('QUIZ', 'Quiz'), ('PROBLEMS', 'Problems')], max_length=10),
        ),
    ]
