# Generated by Django 5.2.4 on 2026-01-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0013_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='unlock_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after Batch Start Date to unlock this content. 0 means available on start date.'),
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('enrollment_end_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='namma_coding_shaale_app.course')),
            ],
        ),
    ]
