# Generated by Django 5.2.4 on 2026-01-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0014_coursecontent_unlock_days_coursebatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseBatch',
            new_name='Batch',
        ),
    ]
