# Generated by Django 5.2.4 on 2026-01-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namma_coding_shaale_app', '0016_usercourse_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namma_coding_shaale_app.batch'),
        ),
    ]
